version: '2.3'

services:
  nemo-eva:
    image: jstriebel/nemo-eva
    build:
      context: .
      target: nemo-eva
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - DISPLAY=:99
    user: ${UID:-1000}:${GID:-1000}

  dev:
    image: jstriebel/nemo-eva-dev
    extends: nemo-eva
    build:
      context: .
      target: nemo-eva-dev
    command: bash

  lint:
    extends: dev
    command: pycodestyle --show-source --show-pep8 .

  test:
    extends:
      service: dev
    command:
      - sh
      - -c
      - >
        Xvfb $$DISPLAY -screen 0 800x600x8 -ac +render -noreset &
        pytest -s

  dev-local:
    extends: dev
    volumes:
      - "./data:/data"
      - "./src:/src"

  test-local:
    extends: test
    volumes:
      - "./data:/data"
      - "./src:/src"

  lint-local:
    extends: lint
    volumes:
      - "./data:/data"
      - "./src:/src"
