version: '2.3'

services:
  nemo-eva:
    image: jstriebel/nemo-eva
    build:
      context: .
      target: nemo-eva
    volumes:
      - "./data:/data"
    environment:
      - TZ=${TZ:-Europe/Berlin}
    user: ${UID:-1000}:${GID:-1000}

  dev:
    image: jstriebel/nemo-eva-dev
    extends: nemo-eva
    build:
      context: .
      target: nemo-eva-dev
    command: bash

  lint:
    extends: dev
    command: pycodestyle --show-source --show-pep8 .

  test:
    extends:
      service: dev
    command: pytest

  dev-local:
    extends: dev
    volumes:
      - "./src:/src"

  test-local:
    extends: test
    volumes:
      - "./src:/src"

  lint-local:
    extends: lint
    volumes:
      - "./src:/src"
