version: '2.3'

services:
  nemo-eva:
    image: jstriebel/nemo-eva
    build:
      context: .
      target: nemo-eva
    command: make
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - DISPLAY=:99
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "8888:8888"

  dev:
    image: jstriebel/nemo-eva-dev
    extends: nemo-eva
    command: sh
    build:
      context: .
      target: nemo-eva-dev

  dev-local:
    extends: dev
    volumes:
      - "./data:/data"
      - "./src:/src"
