version: 2

jobs:
  build_test_push:
    docker:
      - image: docker/compose:1.18.0
    environment:
      UID: 1001
      GID: 1001
      TZ: Europe/Berlin
    steps:
      - run:
          name: Install curl & docker
          command: apk add --no-cache curl docker
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: docker-compose build --pull 
      - run:
          name: Linting
          command: docker-compose run --rm lint


workflows:
  version: 2
  default:
    jobs:
      - build_test_push
